INSERT INTO tags (name) VALUES ('spinoff') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Amrize') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('North-America') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('NYSE') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SIX') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Jan-Jenisch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Fitch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit-rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('upgrade') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Vulcan-Materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('aggregates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('acquisition') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supplementary-cementitious-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SCM') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('sustainability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategic-plan') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Lead-and-Grow') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('2030-targets') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capital-allocation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('portfolio-rotation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('data center') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('liquid cooling') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Chilldyne') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('DDC Solutions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('earnings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q2 FY2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('margin expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategic review') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Europe') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('divestiture') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('portfolio optimization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('steel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tariffs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('protectionism') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('governance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('leadership-change') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CFO') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('audit-committee') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('board-restructuring') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lumber') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('timber') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cabinets') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('furniture') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Section-232') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Trump') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Canada') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mortgage-rates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('affordability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Federal-Reserve') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('30-year-fixed') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('M&A') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building-products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('distribution') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('private-equity') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Brad-Jacobs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mill-closure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Vanderhoof') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('British-Columbia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('restructuring') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('community-impact') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tax-revenue') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('oil-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Brent-crude') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('WTI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EIA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IEA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('innovation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-storage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('concrete') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supercapacitor') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('carbon-concrete') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('NAHB') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('PPI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('residential-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('material-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('softwood-lumber') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('metals') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('resilience') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pricing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('infrastructure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('trends') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('data-centers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('megaprojects') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IIJA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('reauthorization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('federal-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('highway-funding') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst ratings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('price target') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Buy consensus') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('premium valuation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('labor') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('regulations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('contractor-strategy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Construction-Dive') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mobile-glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('portfolio-optimization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AGC-plus-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cement') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IIJA-expiration') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('demand-forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('residential') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('interest-rates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('inflation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('USA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('europe') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('divergence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('margins') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market-dynamics') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-economy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bidding') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('labor-shortage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ConstructConnect') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-trends') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('2026-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('technology') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('modular-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('digital-transformation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('risks') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ENR') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ABC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dealer-channel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HBS-Dealer') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-shortage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('R-and-R') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('KPMG') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('GDP') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('economic-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('two-speed-economy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('unemployment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deals') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('grid-modernization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('valuation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('overvalued') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Buy rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ratings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('renovation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('S-and-P') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('BLS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('employment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('jobs-report') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('nonfarm-payrolls') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-employment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('wages') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capital-raise') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('QXO') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst-ratings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('price-target') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Wells-Fargo') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('JP-Morgan') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buy-rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('global-cement-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('surplus') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capacity') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('aluminum') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('copper') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bid-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst-upgrade') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Raymond-James') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Overweight') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Wells Fargo') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('plumbing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fixtures') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('home improvement') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('workforce') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('demographics') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('consolidation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Bain') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deal-volume') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('valuations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('challenges') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('global') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('flat-glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-efficiency') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Low-E-glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('automotive') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market-size') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('leadership') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('executive appointments') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('turnaround') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('operational efficiency') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('futures') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('framing-lumber') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Moodys') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('water efficiency') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('smart plumbing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market size') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('roofing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('state-of-industry') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mid-term plan') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('digitalization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('North America expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('overhead doors') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('downgrade') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('China') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Hold rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CalPortland') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ready-mix') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('California') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('DOJ') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('antitrust') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HSR-Act') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EBITDA-growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('timberlands') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EWP') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('climate-solutions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Virginia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Oregon') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Georgia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Alabama') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('trade-policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('effective-tariff-rate') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('power') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('transportation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CHIPS-Act') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('amrize') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('holcim') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q4-2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('stocks') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst-estimates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capex') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Philippines') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Luzon') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('terminal') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cement-supply') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Asia-Pacific') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Tokuyama') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Japan') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('domestic-consolidation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cement-sales') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mill-curtailment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('OSB') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('High-Level-Alberta') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capacity-reduction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('impairment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Jefferies') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('doors') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('windows') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ABI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Architecture-Billings-Index') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('nonresidential-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('leading-indicator') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('design-contracts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lumber-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('seasonal-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('rally') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HVAC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AI cooling') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CEO') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Heimo Scheuch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mandate extension') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Dagmar Steinert') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SLOOS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lending-standards') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-loans') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CRE') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('overvaluation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('P/E ratio') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('North America') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q4 2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('free cash flow') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('record shipments') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buyback') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deal-value') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('geopolitics') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-starts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building-permits') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('multifamily') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('single-family') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Census-Bureau') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('insulation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building-codes') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fiberglass') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mineral-wool') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Apple Grove') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('West Virginia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('sheet mill') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EAF') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capacity expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('green steel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS miss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('guidance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dividend') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('goodwill-impairment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lumber-segment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('US-operations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('2026-guidance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('downcycle') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('consumer-confidence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Conference-Board') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('present-situation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('expectations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recession-risk') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recession-signal') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FOMC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('monetary-policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fed-funds-rate') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dissent') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('rate-pause') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('engineering') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FMI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('data centers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Brazil') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Latin America') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('full year 2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bookings record') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('backlog') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('January-2026-data') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AIA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('nonresidential') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('infrastructure-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('economic-growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('consumer-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('economic-data') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('monthly-data') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q3 FYE2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('core earnings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('water technology') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('eagle-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit-ratings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('S&P-Global') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('issuer-ranking') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('wood-products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('REIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('retirement') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('apprenticeship') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('electricians') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('curtain-wall') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('smart buildings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building automation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IoT') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy management') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('occupant-centric') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Canadian-imports') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Mexican-imports') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Panama') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Grupo-Estrella') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('US-aggregates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('imports') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('vietnam') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('MEP') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('electrical') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('wood-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('insulation-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('builders-firstsource') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('digital') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('acquisitions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('homebuilding') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supply-chain') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('home-sales') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('martin-marietta') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q4') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('records') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('NVIDIA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('thermal management') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('reference design') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('gigawatt-scale') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building envelope') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Vision 2030') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EBITDA margin') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q3 FY2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('operating profit decline') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tariff impact') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('guidance revision') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q1 FY2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('guidance raised') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('record backlog') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('transformation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Bosch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('portfolio simplification') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pure-play commercial') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buybacks') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dividends') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EBITDA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('stock buyback') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Section 232') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Calvert') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('electric arc furnace') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('NOES') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('electrical steel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS beat') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue miss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('share buyback') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('record margins') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('organic growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dual sourcing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pure-play HVAC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS-miss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Project-Cutting-Edge') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cost-savings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue decline') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tariff headwinds') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Australia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('quarries') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Maas-Group') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('H1 FY2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('record profit') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Overhead Door') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('access solutions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('security') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('locks') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recovery') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q1 2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('orders') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS guidance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Moderate Buy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FY2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('display') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('chemicals') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('guidance-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('M&A-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('middle-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Capstone') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('US') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lending standards') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction lending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('commercial real estate') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit conditions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('China sourcing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supply chain') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mitigation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('vulcan-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('shipments') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Sell rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('value trap') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-lending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit-conditions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('commercial-real-estate') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bank-lending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Fed-survey') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue-decline') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fiscal-year') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('guidance-revision') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-jobs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('wage-growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('labor-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industrial-products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('webcast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industrial-policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategic-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Deloitte') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pricing power') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('volume-growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('infrastructure-supercycle') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building products distribution') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Kodiak Building Partners') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CEO transition') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('succession planning') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Amit Banati') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('production-curtailments') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('equity-offering') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capital-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('public-works') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('aggregates-demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pricing-power') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CHIPS Act') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('infrastructure spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('full-year-2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('moderate-buy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lumber-valuation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('upside-potential') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mill-closures') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('geographic-diversification') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('outlook-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Warren Buffett') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tariff') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('institutional investment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('steel demand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('glass-reinforcements') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Praana-Group') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('portfolio-transformation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('composites') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('earnings revisions') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buy consensus') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building materials sector') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EPS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('heidelberg-materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('decarbonization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction technology') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('3D printing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('robotics') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('prefabrication') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('digital transformation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industry outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('labor shortage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Section 122') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('trade policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deal volume') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('private equity') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategic buyers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('geopolitical-risk') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('iran') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('homebuilders') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('spring-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('uncertainty') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('immigration') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('H-2B-visa') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-labor') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deportation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building materials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing affordability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('material costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('home building') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('deals outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('collections') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('credit outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('residential construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('UBS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('price targets') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Peter Jackson') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Pete Beckmann') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HMI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('builder-confidence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('incentives') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('M-and-A') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pipeline') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue-miss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q4-miss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('per-ton-profit') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('water-infrastructure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('growth-drivers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('margin-expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('S-and-P-500') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('record-results') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Goldman Sachs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('loss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('goodwill impairment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Alloy Enterprises') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('builder confidence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('home builder sentiment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-services') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('labor-shortages') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('LEI') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('leading-economic-index') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('precast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-methods') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('modular') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing starts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building permits') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('new home sales') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Supreme Court') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IEEPA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('stormwater') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('NDS acquisition') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revenue guidance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('headwinds') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('balance sheet') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('engineered-wood-products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IBS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('TimberStrand') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('product-launch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('asset-exchange') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Quikrete') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cement-divestiture') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('tax-efficient') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Deckorators') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('packaging') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cost-reduction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('share-buyback') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('consumer confidence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('economic outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recession risk') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('consumer spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('retail') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('composite decking') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capacity-expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Buffalo') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Selma') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('composite-decking') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Surestone') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('growth-strategy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FY 2025') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Italcer') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ceramics') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CCUS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('carbon-capture') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Edmonton') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Brevik') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('net-zero') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('RCO') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EBITDA-margin') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cost-discipline') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('price-management') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('US expansion') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Steico') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('comparable sales') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Masonite') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-chemicals') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Grouttech') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Benelux') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Dominican-Republic') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing headwinds') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('domestic production') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('2026 outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('European housing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('product launch') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('chiller') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AquaEdge') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cooling technology') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst-day') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('shareholder-returns') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Omega-Products') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('installation services') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mortgage rates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('interest rates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('homebuying') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-affordability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Freddie-Mac-PMMS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('rate-dip') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Beacon Roofing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('integration') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Brad Jacobs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('EBIT') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('margin') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('post-spinoff') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('free-cash-flow') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('material prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('diesel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('hiring') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction employment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Iran war') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('oil prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('European construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('weather impact') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industry-outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('type-IL') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('disruption') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('lending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('maturity-wall') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bond-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('institutional-capital') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('US operations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cost mitigation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HVAC pricing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AI-infrastructure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('hyperscale') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('sustainable-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cost-report') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pro-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('drywall') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('steel-framing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('kodiak') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Highway-Trust-Fund') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('expiration') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IRE-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('trade-show') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fuel-costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('M&A strategy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('steel-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('hot-rolled-coil') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Nucor') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market trends') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('smart home') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy efficiency') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('IBS 2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CONEXPO') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-technology') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('electrification') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('automation') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('LiquidStack') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('immersion cooling') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('retail security') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('asset protection') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AI infrastructure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('commercial HVAC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Iran-war') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Strait-of-Hormuz') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-crisis') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('asphalt') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strait-of-hormuz') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pulp') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('operating-loss') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('carlisle') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('suppliers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('capital returns') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('shareholder value') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strategic-buyers') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('strong-buy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('JPMorgan') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('iron ore') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('economic-roundup') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ConExpo') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-equipment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industry-event') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('anti-dumping') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('countervailing-duties') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Canadian-lumber') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('project-cancellations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('AGC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('contractor-survey') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('escalation-clauses') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cooling') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fly-ash') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pozzolans') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SCMs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('census-data') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('macro-concerns') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market-trends') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('waterproofing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Colombia') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Holcim-acquisition') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('emerging-markets') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('profit flat') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('margin pressure') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('European market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction outlook') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('UK') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housebuilding') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('commercial') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('PwC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('leverage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('debt') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('investor-day') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('per-ton-target') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('greenfield') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('revision') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Buy-consensus') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('upside') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('building materials pricing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('microsoft') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('meta') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('campus') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('insurance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('risk') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('survey') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('risk-management') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-starts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('regional-analysis') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('manufacturing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recession') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('probability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('GDP-growth') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('forecasts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-impact') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('weather-impact') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q1-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('forecast-trim') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('undervalued') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Stifel') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Hold') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('activist investor') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Ed Garden') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('CEO reversal') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('board changes') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('price-cuts') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('spring-selling-season') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('earnings guidance') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Columbus Mississippi') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('flat rolled') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('ramp-up') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('fed-decision') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('iran-crisis') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('rate-cut-forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('dot-plot') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SEP') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FY2026-estimates') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Hold-rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('earnings-forecast') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('stabilization') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('highway-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('industrials') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('onshoring') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('long-term') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('compounding') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Morgan-Stanley') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Barclays') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('overweight') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q1-results') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Xella') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('European-market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('real-estate-development') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('public-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('earnings preview') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst expectations') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('knife-river') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('montana') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('domestic-supply') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('state-spending') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('construction-projects') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Plasti-Fab') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('MTL') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Bonded Logic') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Iran-conflict') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('material-costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Lowes') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Home Depot') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('FBM') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('GMS') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('SRS Distribution') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pro market') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('pulse-index') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('market-data') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('march-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('executive-order') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('mortgage-credit') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('community-banks') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('housing-policy') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst upgrade') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buy rating') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('analyst-call') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('buying-opportunity') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-spike') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-costs') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Peru') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Latin-America') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Cementos-Pacasmayo') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('17-month-low') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('spring-construction') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('carbon-tax') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supply') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('refinancing') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('COO appointment') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Chief Impact Officer') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('organizational change') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('GDPNow') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Atlanta-Fed') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('steel prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('HRC') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('hot rolled coil') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('commodity') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Kaiser-strike') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('adoption') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('contractors') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('cement-imports') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Mexico') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('supply-shortage') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('domestic-production') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('contract-language') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('scale-to-scope') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('due-diligence') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('BEA') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('third-estimate') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('energy-prices') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('attrition') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('recession-probability') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('new-home-sales') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('roads') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('bridges') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('water') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('Q3-2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('coatings') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('sealants') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('50 percent') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('full customs value') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('metals-recalibration') ON CONFLICT (name) DO NOTHING;
INSERT INTO tags (name) VALUES ('April-2026') ON CONFLICT (name) DO NOTHING;
